-- =============================================================================
-- EVALUACIÓN FINAL TRANSVERSAL - CONSULTA DE BASES DE DATOS
-- NOMBRE ESTUDIANTE: [RODRIGO OLAVARRIA CARRASCO]
-- REPOSITORIO GITHUB: [TU ENLACE AQUÍ]
-- =============================================================================

--------------------------------------------------------------------------------
-- 1. ESTRATEGIA DE SEGURIDAD (CONEXIÓN: SYSTEM / ADMIN)
-- Creación con nombre, clave, TABLESPACE y CUOTA 
--------------------------------------------------------------------------------
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Borrado preventivo para script limpio
DROP USER PRY2205_EFT_CON CASCADE;
DROP USER PRY2205_EFT_DES CASCADE;
DROP USER PRY2205_EFT CASCADE;

-- Dueño de los datos (Owner)
CREATE USER PRY2205_EFT IDENTIFIED BY "Eft_2024_Admin_Pass" 
DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;

-- Desarrollador (Developer)
CREATE USER PRY2205_EFT_DES IDENTIFIED BY "Des_2024_User_Dev" 
DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;

-- Usuario Consulta (Read Only)
CREATE USER PRY2205_EFT_CON IDENTIFIED BY "Con_2024_Query_Read" 
DEFAULT TABLESPACE USERS;

-- Privilegios y Roles (Criterio Pauta: 5 pts)
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PUBLIC SYNONYM, DROP PUBLIC SYNONYM TO PRY2205_EFT;
GRANT CONNECT, RESOURCE, CREATE VIEW TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;


--------------------------------------------------------------------------------
-- 2. ESTRUCTURA Y OPTIMIZACIÓN (CONEXIÓN: PRY2205_EFT - OWNER)
-- Objetos BD (Vistas, Sinónimos, Índices) 
--------------------------------------------------------------------------------

-- OPTIMIZACIÓN : Sinónimos Públicos 
CREATE OR REPLACE PUBLIC SYNONYM SYN_PROFESIONAL FOR PRY2205_EFT.PROFESIONAL;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ASESORIA FOR PRY2205_EFT.ASESORIA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EMPRESA FOR PRY2205_EFT.EMPRESA;

-- OPTIMIZACIÓN : Índices en columnas de búsqueda frecuente
CREATE INDEX IDX_PROF_COMUNA ON PROFESIONAL(CODCOMUNA);
CREATE INDEX IDX_EMP_SECTOR ON EMPRESA(CODSECTOR);
CREATE INDEX IDX_ASESORIA_FECHA ON ASESORIA(INICIO);

-- CONTROL DE ACCESO: Delegación de permisos (WITH GRANT OPTION)
GRANT SELECT ON PROFESIONAL TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON ASESORIA TO PRY2205_EFT_DES WITH GRANT OPTION;
GRANT SELECT ON EMPRESA TO PRY2205_EFT_DES WITH GRANT OPTION;

--------------------------------------------------------------------------------
-- 3. LÓGICA DE NEGOCIO Y OBJETOS (CONEXIÓN: PRY2205_EFT_DES)
-- Criterios: JOINS, GROUP BY, SET, SUBCONSULTAS Y SECUENCIAS
--------------------------------------------------------------------------------

-- A. OBJETO REQUERIDO: Secuencia 
-- Útil para futuros registros de auditoría o nuevas asesorías.
CREATE SEQUENCE SEQ_AUDITORIA_GESTION
START WITH 100
INCREMENT BY 1;

-- REPORTE 1: GESTIÓN DE HONORARIOS 
-- Cumple: Joins, Alias y Funciones de Fila
CREATE OR REPLACE VIEW V_DETALLE_HONORARIOS AS
SELECT 
    UPPER(P.APPPRO || ' ' || P.NOMPRO) AS "PROFESIONAL",
    E.NOMEMPRESA AS "EMPRESA",
    TO_CHAR(A.INICIO, 'DD/MM/YYYY') AS "FECHA_INICIO",
    '$' || TO_CHAR(A.HONORARIO, '999G999G999') AS "HONORARIO_BRUTO",
    '$' || TO_CHAR(ROUND(A.HONORARIO * 0.10), '999G999G999') AS "RETENCION_SISTEMA"
FROM SYN_PROFESIONAL P 
JOIN SYN_ASESORIA A ON P.RUTPROF = A.RUTPROF
JOIN SYN_EMPRESA E ON A.IDEMPRESA = E.IDEMPRESA
ORDER BY A.HONORARIO DESC;

-- REPORTE 2: RESUMEN EJECUTIVO POR SECTOR 
-- Cumple: Funciones de Grupo, GROUP BY y HAVING 

CREATE OR REPLACE VIEW V_ESTADISTICA_SECTOR AS
SELECT 
    E.CODSECTOR AS "ID_SECTOR",
    COUNT(*) AS "TOTAL_CONTRATOS",
    '$' || TO_CHAR(SUM(A.HONORARIO), '999G999G999') AS "TOTAL_RECAUDADO",
    '$' || TO_CHAR(ROUND(AVG(A.HONORARIO)), '999G999G999') AS "PROMEDIO_VALOR"
FROM SYN_ASESORIA A
JOIN SYN_EMPRESA E ON A.IDEMPRESA = E.IDEMPRESA
GROUP BY E.CODSECTOR
HAVING COUNT(*) > 5;

-- REPORTE 3: ANÁLISIS DE MERCADO 
-- Cumple: Operadores SET (UNION) y SUBCONSULTAS 
CREATE OR REPLACE VIEW V_COMPARATIVA_MERCADO AS
SELECT 'ASESORÍAS TOP (SOBRE EL PROMEDIO)' AS "TIPO_DATO", COUNT(*) AS "CANTIDAD", SUM(HONORARIO) AS "MONTO"
FROM SYN_ASESORIA
WHERE HONORARIO > (SELECT AVG(HONORARIO) FROM SYN_ASESORIA)
UNION
SELECT 'ASESORÍAS ESTÁNDAR (BAJO EL PROMEDIO)' AS "TIPO_DATO", COUNT(*) AS "CANTIDAD", SUM(HONORARIO) AS "MONTO"
FROM SYN_ASESORIA
WHERE HONORARIO <= (SELECT AVG(HONORARIO) FROM SYN_ASESORIA);

-- Ejecutar conectado como PRY2205_EFT_DES
GRANT SELECT ON V_DETALLE_HONORARIOS TO PRY2205_EFT_CON;
GRANT SELECT ON V_ESTADISTICA_SECTOR TO PRY2205_EFT_CON;
GRANT SELECT ON V_COMPARATIVA_MERCADO TO PRY2205_EFT_CON;

SELECT * FROM PRY2205_EFT_DES.V_DETALLE_HONORARIOS;
SELECT * FROM PRY2205_EFT_DES.V_ESTADISTICA_SECTOR;
SELECT * FROM PRY2205_EFT_DES.V_COMPARATIVA_MERCADO;

