/* =============================================================================
   EFT: CONSULTA DE BASES DE DATOS
   AUTOR: RODRIGO OLAVARRÍA
   ============================================================================= */

-- PASO 1: CONECTADO COMO SYSTEM
SHOW USER;
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Limpieza (Opcional para pruebas)
DROP USER PRY2205_EFT CASCADE;
DROP USER PRY2205_EFT_DES CASCADE;
DROP USER PRY2205_EFT_CON CASCADE;
DROP ROLE PRY2205_ROL_D;
DROP ROLE PRY2205_ROL_C;

-- Creación de Roles y Usuarios 
CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;

CREATE USER PRY2205_EFT IDENTIFIED BY "Eft.2024.Admin.Pass" DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;
CREATE USER PRY2205_EFT_DES IDENTIFIED BY "Des.2024.Dev.Pass" DEFAULT TABLESPACE USERS QUOTA 10M ON USERS;
CREATE USER PRY2205_EFT_CON IDENTIFIED BY "Con.2024.User.Pass" DEFAULT TABLESPACE USERS;

-- Privilegios de Sistema
GRANT CONNECT, RESOURCE, CREATE VIEW, CREATE PUBLIC SYNONYM, CREATE TABLE TO PRY2205_EFT;
GRANT CONNECT, RESOURCE, CREATE TABLE TO PRY2205_EFT_DES;
GRANT CREATE SESSION TO PRY2205_EFT_CON;

GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;




-- =============================================================================
-- PASO 2: CONECTADO COMO PRY2205_EFT (DUEÑO)
-- =============================================================================
SHOW USER;

--EJECUTAR PRY2205_EFT_S9CREAESQUEMAPOBLADO--

-- Privilegios de objeto para el Desarrollador (Pauta Item 5)
GRANT SELECT ON PROFESIONAL TO PRY2205_ROL_D;
GRANT SELECT ON ISAPRE TO PRY2205_ROL_D;
GRANT SELECT ON PROFESION TO PRY2205_ROL_D;

-- CREACIÓN DE SINÓNIMOS PÚBLICOS (Pauta Item 8)
CREATE OR REPLACE PUBLIC SYNONYM SYN_PROFESIONAL FOR PRY2205_EFT.PROFESIONAL;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ISAPRE FOR PRY2205_EFT.ISAPRE;
CREATE OR REPLACE PUBLIC SYNONYM SYN_PROFESION FOR PRY2205_EFT.PROFESION;
CREATE OR REPLACE PUBLIC SYNONYM SYN_ASESORIA FOR PRY2205_EFT.ASESORIA;
CREATE OR REPLACE PUBLIC SYNONYM SYN_EMPRESA FOR PRY2205_EFT.EMPRESA;

-- CASO 3: Vista de Empresas y Optimización (Pauta Item 4 y 8)
CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT 
    E.NOMEMPRESA AS "NOMBRE EMPRESA",
    COUNT(A.IDEMPRESA) AS "CANTIDAD ASESORIAS",
    ROUND(AVG(A.HONORARIO)) AS "PROMEDIO HONORARIOS",
    CASE WHEN COUNT(A.IDEMPRESA) > 5 THEN 'CLIENTE PREMIUM' ELSE 'CLIENTE' END AS "ESTADO CLIENTE",
    CASE WHEN COUNT(A.IDEMPRESA) > 5 THEN '1 ASESORIA GRATIS' ELSE '1 ASESORIA 30% DESCUENTO' END AS "OBSERVACION"
FROM EMPRESA E
JOIN ASESORIA A ON E.IDEMPRESA = A.IDEMPRESA
GROUP BY E.NOMEMPRESA;

GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_ROL_C;
CREATE OR REPLACE PUBLIC SYNONYM VW_EMPRESAS_ASESORADAS FOR PRY2205_EFT.VW_EMPRESAS_ASESORADAS;

-- OPTIMIZACIÓN: Índice (Pauta Item 8) - Columna 'FIN' según script de poblado
CREATE INDEX IDX_ASESORIA_FECHAS ON ASESORIA(FIN);




-- =============================================================================
-- PASO 3: CONECTADO COMO PRY2205_EFT_DES (DESARROLLADOR)
-- =============================================================================
SHOW USER;

-- CASO 2: Cartola de Profesionales con Cálculos NVL y CASE (Pauta Item 3, 4 y 5)
CREATE TABLE CARTOLA_PROFESIONALES AS
SELECT 
    P.RUTPROF AS "RUT",
    P.NOMPRO || ' ' || P.APPPRO AS "NOMBRE_COMPLETO",
    PR.NOMPROFESION AS "PROFESION",
    I.NOMISAPRE AS "ISAPRE",
    P.SUELDO AS "SUELDO_BASE",
    -- Cálculo Comisión (NVL para manejar nulos como 0)
    NVL(P.COMISION, 0) * P.SUELDO / 100 AS "VALOR_TOTAL_COMISION",
    -- Cálculo Honorarios según Tabla de Rangos Forma C
    CASE 
        WHEN P.SUELDO <= 500000 THEN ROUND(P.SUELDO * 0.05)
        WHEN P.SUELDO BETWEEN 500001 AND 900000 THEN ROUND(P.SUELDO * 0.08)
        ELSE ROUND(P.SUELDO * 0.12)
    END AS "VALOR_HONORARIOS"
FROM SYN_PROFESIONAL P
JOIN SYN_ISAPRE I ON P.IDISAPRE = I.IDISAPRE
JOIN SYN_PROFESION PR ON P.IDPROFESION = PR.IDPROFESION;

GRANT SELECT ON CARTOLA_PROFESIONALES TO PRY2205_ROL_C;



-- =============================================================================
-- PASO 4: CONECTADO COMO PRY2205_EFT_CON (CONSULTOR)
-- =============================================================================
SHOW USER;

-- Demostración de uso de Sinónimos y Vistas para el perfil Consultor
SELECT * FROM VW_EMPRESAS_ASESORADAS ORDER BY "NOMBRE EMPRESA" ASC;
SELECT * FROM PRY2205_EFT_DES.CARTOLA_PROFESIONALES;